services:

  mariadb:
    build:
      context: ./requirements/mariadb
    image: mariadb
    container_name: mariadb
    restart: always
    networks:
    - network


  wordpress:
    build:
      context: ./requirements/wordpress
    container_name: wordpress
    restart: always
    networks:
     - network


  nginx:
    build:
      context: ./requirements/nginx
    container_name: nginx
    restart: always
    networks:
     - network
    ports:
      - 443:443

networks:
  network: